import = ["/home/fuzz/.config/alacritty/rosepine/rose-pine.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12.5

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Medium Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.8
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
