#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
# $HOME/.config/polybar/launch.sh &
xfce4-panel --disable-wm-check &
picom --config $HOME/.config/bspwm/picom.conf &
xsetroot -cursor_name left_ptr &
feh --no-fehbg --bg-fill $HOME/Pictures/walls/moon2.png

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 5
# bspc config top_padding 30

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc rule -a '*:*:Picture-in-Picture' state=floating rectangle=600x300+1300+760 focus=off
bspc rule -a Xfce4-appfinder state=floating
bspc rule -a scrcpy state=floating
bspc rule -a Gui.pyc state=floating
