icons_format = "{icon}"

[theme]
theme = "native"

[icons]
icons = "awesome6"

[[block]]
block = "cpu"
interval = 1
format = "$icon $utilization"
format_alt = "$icon $frequency{ $boost|}"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon /: $available.eng(w:2)"

[[block]]
block = "memory"
format = "$icon $mem_total_used_percents.eng(w:2)"
format_alt = "$icon_swap $swap_used_percents.eng(w:2)"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
format = "$icon $percentage {$time |}$power"
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "kdeconnect"
format = " $icon {$bat_icon $bat_charge |}{$notif_icon |}{$network_icon$network_strength $network_type |}"
bat_good = 101

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%a %d/%m %I:%M %p')"
