icons_format = "{icon}"

[theme]
theme = "plain"

[icons]
icons = "awesome6"

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon /: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
device = "BAT0"
format = " $icon $percentage "

[[block]]
block = "battery"
device = "BAT1"
format = " $icon $percentage "

[[block]]
block = "time"
interval = 30
format = " $timestamp.datetime(f:'%a %d/%m %I:%M %p') "

